"""created schema

Revision ID: 71bce1b6bf34
Revises: 18eacb64ceb2
Create Date: 2022-12-15 12:24:55.817837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bce1b6bf34'
down_revision = '18eacb64ceb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_id'), 'auth', ['id'], unique=False)
    op.drop_table('blog_table')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.add_column('blogs', sa.Column('name', sa.String(), nullable=True))
    op.add_column('blogs', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('blogs', 'title')
    op.drop_column('blogs', 'body')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'description')
    op.drop_column('blogs', 'name')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('blog_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='blog_table_pkey')
    )
    op.drop_index(op.f('ix_auth_id'), table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###
